#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm nano-staged
   "docs:build": "vuepress build docs",
    "docs:dev": "vuepress dev docs",
    "docs:clean-dev": "vuepress dev docs --clean-cache",
    "lint": "prettier --check --write . && markdownlint docs/**/*.md"
    "lint": "prettier --check --write . && markdownlint docs/**/*.md",
    "prepare": "husky install"
  },
  "nano-staged": {
    ".ts,.scss": "prettier --write",
    ".md": [
      "prettier --write",
      "markdownlint"
    ]
  },
  "dependencies": {
    "@vuepress/client": "2.0.0-beta.61",
    "husky": "^8.0.3",
    "markdownlint-cli": "0.33.0",
    "nano-staged": "^0.8.0",
    "prettier": "2.8.8",
    "vue": "3.2.47",
    "vuepress": "2.0.0-beta.61",
